### ISSUE TITLE
I don't get the advantages over just typing HTML

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/legumeinfo-jekyll-theme#1]
I look forward to hearing why Jekyll is a good solution over just typing HTML into files according to an established framework. I've set this up on my laptop and I'm staring at exactly what I'd get with a directory index. So here's my initial issue to state that this seems like overkill to me, which adds maintenance and deployment tasks to an otherwise fairly simple concept (given that we all know how to type img and h1 and p tags).

**Comment by adf-ncgr** [comment]
classic @sammyjava attitude to web dev :) 
(not that I necessarily disagree with it, but I suspect the kids will have a persuasive argument)
Of course, the main requirement of any solution is that we be able to embed a twitter feed...

**Comment by sammyjava** [comment]
Closing this, I believe it has been solved by adf-ncgr above. :)
