### ISSUE TITLE
Gem can't find legumeinfo-jekyll-theme

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/legumeinfo-jekyll-theme#2]
Where do I put it? _(I'm assuming that there IS a way for Jekyll to load it locally, rather than from the aether. Seems weird that it wouldn't be able to.)_
```
shokin@morangie:~/sams-test-site$ ls
404.html  about.markdown  _config.yml  Gemfile  Gemfile.lock  index.markdown  legumeinfo-jekyll-theme  _posts  _site
shokin@morangie:~/sams-test-site$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'legumeinfo-jekyll-theme x86_64-linux' in any of the gem sources listed in your Gemfile.

shokin@morangie:~/sams-test-site$ gem install legumeinfo-jekyll-theme
ERROR:  Could not find a valid gem 'legumeinfo-jekyll-theme' (>= 0) in any repository
```
(I could probably figure it out, but since I'm following your instructions, you need to tell me in your instructions.)

**Comment by adf-ncgr** [comment]
I'm not sure this is relevant to how @alancleary wants to approach the short term solution to this but FWIW, here is the approach @nathanweeks took to solve this in the containerized version:

git diff 79c73421da19632123e3c21bb56b172d5742000e 9d7072e5d6febf7beaf42773612021d060ed3bb7 _config.yml
diff --git a/_config.yml b/_config.yml
index b0cde81..5a1c1e2 100644
--- a/_config.yml
+++ b/_config.yml
@@ -32,10 +32,9 @@ github_username: legumeinfo
 newsletter: http://eepurl.com/cX_JjL

 # Build settings
-remote_theme: legumeinfo/legumeinfo-jekyll-theme@1d0c318
+theme: legumeinfo-jekyll-theme
 plugins:
   - jekyll-feed
-  - jekyll-remote-theme

 # Exclude from processing.
 # The following items will not be processed, by default.
@@ -45,8 +44,7 @@ plugins:
 # Excluded items can be processed by explicitly listing the directories or
 # their entries' file path in the `include:` list.
 #
-exclude:
-  - docker-compose.yml
+# exclude:
 #   - .sass-cache/

**Comment by sammyjava** [comment]
I've got the theme: command in _config.yml. Gem doesn't find the theme. I presume it's just a location thing. I'm not using Docker, I'm rolling my own. (I'm not a huge fan of Docker for stuff like this, TBH, I like to build stuff from scratch for this sort of getting-to-know-the-code task.)

**Comment by sammyjava** [comment]
OK, I got it, I have to actually replace the local Jekyll files with the theme files, thereby breaking the theme repo. So it's not really designed to handle modular standalone themes. Basically, clone the theme repo first and then build the site from there. The Gem theme is really mandatory to keep things separate, which I consider being a slightly bad design.

https://jekyllrb.com/docs/themes/#converting-gem-based-themes-to-regular-themes

**Comment by alancleary** [comment]
@sammyjava You can build and install the theme's GEM locally instead of copying the files:
```bash
cd legumeinfo-jekyll-theme
gem build legumeinfo-jekyll-theme.gemspec
gem install ./legumeinfo-jekyll-theme-0.0.0.gem
```
Then it's just a matter of following the installation instructions in the [Legumeinfo Jekyll Theme readme](https://github.com/legumeinfo/legumeinfo-jekyll-theme/blob/main/README.md#installation).

**Comment by sammyjava** [comment]
Cool. Thanks. That makes sense.
