### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/legumeinfo-jekyll-theme#7]
We should add a code of conduct file, specifically, from the contributor covenant: https://www.contributor-covenant.org/version/2/0/code_of_conduct/. We just need to decide what the contact email will be.

**Comment by adf-ncgr** [comment]
IIRC we decided that opensource@ncgr.org would be as good as anything else we could dream up. Still need to make that resolve to an actual mailbox though.

**Comment by alancleary** [comment]
Done in commit 65e6e48ca538ce7c83441edd3a357620c6ab70fe
